### PR TITLE
update to svelte 4, also update other packages and version number

### PR DESCRIPTION
**Pull request by jbirtel**
I updated dependencies including support for Svelte v4. Maybe you see that PR and can merge it

### CODE REVIEW

**Comment by micha-lmxt** [comment]
Thank you for the pull-request. I'll push to npm over the weekend

**Comment by jbirtel** [comment]
Thanks for your answer!
I just saw that I forgot to really update the svelte dependency. But I'm doing that in another commit.
Also, I did not test the other dependencies.

**Comment by AdamGEmerson** [comment]
Perfect timing!  I want to give this library a shot but literally just migrated to svelte 4 this morning.

**Comment by jbirtel** [comment]
Thank you for merging!

**Pull request merged**
