### PR TITLE
Svelte updates compatibility

### PR DESCRIPTION
**Pull request by JonathonRP**
After testing in project there was still some component type alignment issues between lib components and svelte 5.
this should fix that also, add option to build with svelte and vite with svelte-package command. rollup configuration is still there so the addition changes nothing if unused but helps future proof project

### CODE REVIEW

**Comment by JonathonRP** [comment]
for using vite:build svelte-package
after "type": "module"
```json
"svelte": "src/index.js",
"types": "./dist/index.d.ts",
"svelte": "./dist/index.js",
"exports": {
   ".": {
     "types": "./dist/index.d.ts",
     "svelte": "./dist/index.js",
     "import": "./dist/index.js"
  },
  "./package.json": "./package.json"
},
```

**Comment by JonathonRP** [comment]
@micha-lmxt hoping to get this merged soon

**Comment by JonathonRP** [comment]
@micha-lmxt any word on npm release?

**Comment by JonathonRP** [comment]
@micha-lmxt npm release?

**Comment by micha-lmxt** [comment]
It's released

**Pull request merged**
